---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubernetes
  version: 0.1.0
  annotations:
    categories: Kubernetes
    chartDescription: Injects kubernetes chaos experiment
    executionPlane: "kubernetes"
spec:
  displayName: Kubernetes
  categoryDescription: >
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.
  faults:
    - name: pod-autoscaler
      description: It injects pod-autoscaler chaos in a Kubernetes pod.
      displayName: "aks-primary-failure"
  keywords:
    - Kubernetes
  maintainers:
    - name: Sunny
      email: sunny.meska@uipath.com
  minKubeVersion: 1.12.0
  icon:
    - url: https://github.com/litmuschaos/chaos-charts/blob/master/faults/kubernetes/icons/kubernetes.png
      mediatype: image/png
