---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: aws-chaos
  namespace: default
spec:
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: ebs-loss-by-id
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # set chaos duration (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '30'

            # set target EBS volume ID
            - name: EBS_VOLUME_ID
              value: ''

            # provide the region name of the instance
            - name: REGION
              value: ''
